# Generated by Django 3.2.9 on 2021-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211229_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='idd',
            new_name='id',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='users.Products'),
        ),
    ]
