# Generated by Django 3.2.10 on 2021-12-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20211230_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='q',
            field=models.IntegerField(default=1),
        ),
    ]
