# Generated by Django 3.2.9 on 2022-01-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20220114_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name_locale',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
