# Generated by Django 3.2.10 on 2022-01-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220116_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitems',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.package'),
        ),
    ]
