# Generated by Django 3.2.10 on 2022-01-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_packageitems_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.products'),
        ),
    ]
