# Generated by Django 3.2.10 on 2022-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_packageitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
